### ISSUE TITLE
Compile before publishing

### ISSUE THREAD

**Issue by dwarcake** [OraOpenSource/apex-nitro#199]
### Issue Description
I think it would be usefull, maybe with an option at project level, to compile the 'src' directory to the 'dist' directory right before publishing your project.

Example:
Was working on a feature-branch (with AFEB runnig). When I was done I stopped AFEB and merged my changes into my develop branch.
After that I published the develop branch to APEX, without starting AFEB again.
Since the latest files in my "dist" folder were those of the feature branch, these ones got published into my application altho I was expecting he'd compile/copy the files again to the "dist" folder. 

For me it was kinda confusing.
What's your opinion on this?

### APEX Front-End Boost Version
v3.1.3

**Comment by vincentmorneau** [comment]
Thanks for bringing this to me, I think it's a good idea. Actually I wouldn't even make it an option, it should be the default behavior.

I'll see how to implement this.

**Comment by vincentmorneau** [comment]
fixed in https://github.com/OraOpenSource/apex-nitro/commit/0866ee0bc4668dfeab8fae2bfa2399146446af16
