### ISSUE TITLE
SQLcl Database Connect String don't show password in clear

### ISSUE THREAD

**Issue by maxime-tremblay** [OraOpenSource/apex-nitro#202]
### Issue Description
In the project configuration page, it would be good to have the SQLcl Database Connect String split up into the different parts (e.g. user, pass, host, port, sid).
That way the password item could be using a password type element, so that it's not displayed in clear.

### APEX Nitro Version
v4.0.0 beta1

### Operating System
Windows 7

### Node Version
v6.11.0

### Browser
Chrome v58

### APEX Version
v5.1.1

### Web Server
ORDS 3.0.9, Tomcat 7

**Comment by vincentmorneau** [comment]
Agreed. Will address in a minor release.

**Comment by vincentmorneau** [comment]
After some research, I will be using this module to deal with the password: https://github.com/kelektiv/node.bcrypt.js
