### ISSUE TITLE
Publish application with an alias

### ISSUE THREAD

**Issue by maxime-tremblay** [OraOpenSource/apex-nitro#203]
### Issue Description
The file publish is not working when using an application URL with an application alias instead of the application id.

### APEX Nitro Version
v4.0.0 beta1

### Operating System
Windows 7

### Node Version
v6.11.0

### Browser
Chrome v58

### APEX Version
v5.1.1

### Web Server
ORDS 3.0.9, Tomcat 7

### Web Server
[Example: ORDS 3.0.9, Tomcat 7]

### Project configuration screenshot
![publish with alias](https://user-images.githubusercontent.com/15253364/27037173-1e5a9fd2-4f55-11e7-9721-1e0e3d1e4d1c.png)

**Comment by vincentmorneau** [comment]
Good find! Thank you!

**Comment by vincentmorneau** [comment]
https://github.com/vincentmorneau/apex-publish-static-files/commit/35f9cb85775874d54a51499a57853f2e6bd62e5a should do it. Please run `npm update -g apex-nitro`
