### ISSUE TITLE
Project Configuration - Add an "Add New" button

### ISSUE THREAD

**Issue by maxime-tremblay** [OraOpenSource/apex-nitro#204]
### Issue Description
In the project configuration page, it would be useful to have an "Add New" button in the Actions section.

### APEX Nitro Version
v4.0.0 beta1

### Operating System
Windows 7

### Node Version
v6.11.0

### Browser
Chrome v58

### APEX Version
v5.1.1

### Web Server
ORDS 3.0.9, Tomcat 7

**Comment by vincentmorneau** [comment]
Completely agree. Thanks for bringing this up.
