### ISSUE TITLE
NodeJs Minimum Requirement

### ISSUE THREAD

**Issue by maxime-tremblay** [OraOpenSource/apex-nitro#205]
### Issue Description
Is there a NodeJs minimum requirement. I first installed APEX Nitro with the NodeJs v4.4. When I started a project I had an error with Grunt which resulted in the dist folder being not created.
I then installed NodeJs v6.11, reinstalled APEX Nitro and everything worked as expected.
Could be a good thing to add a note in the project's description specifying the minimum requirement of NodeJs just to prevent others from going through this.

### APEX Nitro Version
v4.0.0 beta1

### Operating System
Windows 7

### Node Version
v4.4 -> v6.11.0

### Browser
Chrome v58

### APEX Version
v5.1.1

### Web Server
ORDS 3.0.9, Tomcat 7

**Comment by vincentmorneau** [comment]
We'll make Node.js 6 the minimum requirement, as it's been LTS for a long time already.
