### ISSUE TITLE
Deprecating Setup Option 2

### ISSUE THREAD

**Issue by vincentmorneau** [OraOpenSource/apex-nitro#206]
I'm thinking of deprecating option 2 here: https://github.com/OraOpenSource/apex-nitro/blob/master/docs/setup.md#option-2-custom-application-item

Reasons:
1) APEX 5.1 has AJAX based validations so we don't see the state where Nitro doesn't load anymore
2) Option 1 refers to `apex_application.g_flow_images` to replace `#APP_IMAGES#`, but we could also document
   - `apex_application.g_company_images` for `#WORKSPACE_IMAGES#`
   - `apex_application.g_theme_file_prefix` for `#THEME_IMAGES#`
3) Makes overall setup easier so this helps for the project adoption

@martindsouza and @maxime-tremblay I would love your opinion on this.

**Comment by dwarcake** [comment]
That addition to the documentation would be helpfull indeed.
I use WORKSPACE_IMAGES all the time ( also the reason why I asked for the addition of that feature a few releases back, thank you for that).

Now it's possible to choose where to upload but it's not clear that, for #WORKSPACE_IMAGES# to work, you have to alter the application process.

**Comment by vincentmorneau** [comment]
@dwarcake you're right. Whether I choose to deprecate option 2 or not, this needs to be added to the doc. Thanks for your input.

**Comment by vincentmorneau** [comment]
after discussing with @martindsouza and @maxime-tremblay, I think we can safely merge them into something like 

```sql
declare
    l_cookie owa_cookie.cookie;
begin
    l_cookie := owa_cookie.get('oos-apex-nitro');

    if l_cookie.vals.count > 0 then
      /* Use one or more of the following depending on the files location */
      -- :G_APP_IMAGES := l_cookie.vals(1);
      -- apex_application.g_image_prefix      := l_cookie.vals(1);
      -- apex_application.g_company_images    := l_cookie.vals(1);
      -- apex_application.g_flow_images       := l_cookie.vals(1);
      -- apex_application.g_theme_file_prefix := l_cookie.vals(1);
    end if;
end;
```
