### ISSUE TITLE
Test connection

### ISSUE THREAD

**Issue by dwarcake** [OraOpenSource/apex-nitro#208]
Possible enhancement

It can be usefull to have a button to test the database connection entered in the JSON project configurator.
When you made a typo, this gives an error when you try to publish your files.

![image](https://user-images.githubusercontent.com/4263208/28160123-80a60d70-67bf-11e7-8141-e2204690337d.png)

**Comment by vincentmorneau** [comment]
Thanks for the suggestion, I think it's a good idea but falls out of scope at this time.

In the next beta, here's what the connect string will look like:

![image](https://user-images.githubusercontent.com/5391291/28171444-10e5c392-67ae-11e7-894b-2ceb43113999.png)

I believe this will reduce the possibility of make errors.

From a technical perspective, APEX Nitro uses [JSON Local Configurator](https://github.com/vincentmorneau/json-local-configurator) to produce these forms. Having a link to validate the SQL connection would break the purpose of generating forms from JSON.

Keep the suggestions coming, you always have good ideas ;) 

Also beta-2 will be published soon, which will resolve https://github.com/OraOpenSource/apex-nitro/issues/199

**Comment by dwarcake** [comment]
The screen of the next beta will surely make it easier :-)

But is it possible to change the placeholder ?
The placeholder is showing ".../sid" but it has to be "...:sid".

Just had a problem ealier today because the database I was trying to connect to was using "service name" instead of "SID".
Since the placeholder showed "/sid" I entered ":service_name" ( I knew it had to be the opposite but always mix these two up )

Later it showed that it has to be ":sid" and "/service_name"

**Comment by vincentmorneau** [comment]
Good point. What should the label/placeholder be?

**Comment by dwarcake** [comment]
For SID:  "user/pass@database:port:sid"
For Service Name: "user/pass@database:port/servicename"

**Comment by dwarcake** [comment]
The difference is explained here:
https://stackoverflow.com/questions/43866/how-sid-is-different-from-service-name-in-oracle-tnsnames-ora

I think ServiceName will be the most used notation ( with "/ServiceName" at the end of the connectionstring)
In some cases, I don't know if there's a specific reason, I have a connection defined by SID and I do not know the ServiceName.
In that case, if SID and ServiceName are different, you'll have to use the ":SID" notation to connect to the database.

**Comment by vincentmorneau** [comment]
Starting from beta-2, there will be 4 options:

- Basic with SID
- Basic with Service Name
- Basic with TNS
- Custom connection string
