### ISSUE TITLE
APEX-nitro is not applying changes

### ISSUE THREAD

**Issue by onlygecko** [OraOpenSource/apex-nitro#215]
### Issue Description
I've set up APEX-Nitro according to the documentation (I think so), but file changes are not applied.

I have a small project on which I'd like to test APEX Nitro. The installation threw some warnings but no errors. I've set up the application process within APEX for the _application static files_. From the _basic-demo_ I've uploaded the app.css to #APP_IMAGES#css/app.css and added the css link to the 101 page.

The project configuration is the following:

```json
{
    "bestof": {
        "mode": "basic",
        "appURL": "http://oraclevm:8080/apex/f?p=100",
        "srcFolder": "/home/gecko/Downloads/apex-nitro-master/examples/demo-basic/src",
        "js": {
            "processor": "default",
            "concat": false,
            "library": false
        },
        "css": {
            "language": "css",
            "concat": false
        },
        "browsersync": {
            "notify": false,
            "ghostMode": false
        },
        "header": {
            "enabled": false
        },
        "apex": {
            "openBuilder": false,
            "apexDestination": "application"
        }
    }
}
```

After launching APEX-Nitro I've edited the app.css (simply changed the color). APEX-Nitro recognizes the change but nothing happens further...

Do I miss something obvious? Where should I look for mistakes? 

### APEX Nitro Version
v4.0.0 beta1

### Operating System
Linux (Debian Testing)

### Node Version
v6.11.2

### Browser
Firefox 52.3.0 ESR

### APEX Version
v5.1.2

### Web Server
ORDS 3.0.9, Tomcat 8

**Comment by vincentmorneau** [comment]
What does your application process looks like? I realize this is confusing
because the current documentation shows the code for beta5, but you
installed the default release (beta1).

Application process code has changed in between beta 1 and 5.

I will improve this in the future by creating branches in this repo.

**Comment by onlygecko** [comment]
Thanks for your response and the tip. I had a look at the doc for 4.0.0 beta 1 and now it's working. :-)
