### ISSUE TITLE
UnhandledPromiseRejectionWarning: Unhandled promise rejection

### ISSUE THREAD

**Issue by isabolic** [OraOpenSource/apex-nitro#216]
when running command apex-nitro config  I got an error
UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Exited with code 3

### APEX Nitro Version
APEX Nitro version 4.0.0-beta.1

### Operating System
Linux

### Node Version
v6.11.0

### APEX Version
5.1.1

### Web Server
oracle Apache PL/SQL module

![image](https://user-images.githubusercontent.com/1404432/29910632-e6c043c8-8e2a-11e7-8e63-2dcba05f72f9.png)

**Comment by vincentmorneau** [comment]
Thanks for reporting this.

Are you willing to try 4.0.0-beta.5? Much has changed regarding the config.

Please reinstall by doing `npm install -g apex-nitro@4.0.0-beta.5` And make sure your application process looks like this: https://github.com/OraOpenSource/apex-nitro/blob/master/docs/setup.md

**Comment by isabolic** [comment]
hello @vincentmorneau 
tnx for the suggestion but I still get the same error

![image](https://user-images.githubusercontent.com/1404432/30060156-7a1680c2-9242-11e7-95cb-5c5ce193e70c.png)

**Comment by vincentmorneau** [comment]
Thanks @isabolic this definitely looks like a bug. I'm going to try to simulate in a Linux environment soon.

1. Is `test` a new project you are trying to edit, or are you trying to create `test`?
2. Can you post a screenshot when running: `apex-nitro list`

**Comment by isabolic** [comment]
@vincentmorneau no problem
1. I'm trying to create my first project
2. This is the first project, also you can see more info about linux OS
![image](https://user-images.githubusercontent.com/1404432/30064619-975b10e8-9252-11e7-9548-fc41010572dc.png)

**Comment by vincentmorneau** [comment]
@isabolic are you able to test on any other system? I tried on many different environment and never get the error.

Or maybe you can export a VM and share it to me?

**Comment by isabolic** [comment]
@vincentmorneau I have fixed it, tnx for your support

**Comment by vincentmorneau** [comment]
That's great to hear, but what was the problem?

**Comment by isabolic** [comment]
@vincentmorneau it runs when I start X server. It open browser for configuration. I thought it will ask for configuration from command line, something like "npm init"
