### ISSUE TITLE
Can't publish files to APEX

### ISSUE THREAD

**Issue by mgoricki** [OraOpenSource/apex-nitro#217]
### Issue Description
I've tried to publish it to local database or to the remote server but the error is the same:
MG-MacBook-Pro:~ Marko$ apex-nitro publish rogla_local

    _     ____   _____ __  __    _   _  _  _
   / \   |  _ \ | ____|\ \/ /   | \ | |(_)| |_  _ __  ___
  / _ \  | |_) ||  _|   \  /    |  \| || || __|| '__|/ _ \
 / ___ \ |  __/ | |___  /  \    | |\  || || |_ | |  | (_) |
/_/   \_\|_|    |_____|/_/\_\   |_| \_||_| \__||_|   \___/

is now processing your files...
...Done!
Uploading to 177 - Application Static Files...

SQLcl: Release 4.2.0.16.175.1027 RC on Wed Sep 06 10:27:10 2017

Copyright (c) 1982, 2017, Oracle.  All rights reserved.

Connected to:
Oracle Database 11g Express Edition Release 11.2.0.2.0 - Production

Could not load file: "/usr/local/lib/node_modules/apex-nitro/node_modules/apex-publish-static-files/lib/distUpload.js"

SQL> 
Disconnected from Oracle Database 11g Express Edition Release 11.2.0.2.0 - Production

Files were uploaded successfully.

### APEX Nitro Version
APEX Nitro version 4.0.0-beta.5

### Operating System
macOS Sierra 10.12.6

### Node Version
v6.11.2

### Browser
Version 60.0.3112.101 (Official Build) (64-bit)

### APEX Version
5.1.2.00.09

### Web Server
ORDS 3.0.11

### Project configuration screenshot
![nitro](https://user-images.githubusercontent.com/3269338/30102143-f635fd84-92ee-11e7-906f-6baefcf73115.png)

**Comment by vincentmorneau** [comment]
Marko, can you try changing the connection type from SID to Service Name?

APEX Nitro is building a connection string based on the information above.

My understanding is that
For SID: "user/pass@database:port:sid"
For Service Name: "user/pass@database:port/servicename"

So maybe you need to switch to Service Name. Let me know.

**Comment by mgoricki** [comment]
I think connection is ok. I've tried with service name with remote server and the error is the same. If I change anything from connection I'm getting connection error like this on:
![image](https://user-images.githubusercontent.com/3269338/30126982-fc8925b8-933d-11e7-8e6b-4f926a11e44a.png)

**Comment by vincentmorneau** [comment]
You're right.

Is sqlcl really accessible through the `sql` environment variable (path)?

What if you excplicitely put the path to sqlcl like `YOUR_PATH/sqlcl/bin/sql`

**Comment by mgoricki** [comment]
Yes. I've tried with absolute path. Same thing. I think connection and SQLCl are ok.
You can see that it connects to the database:
_SQLcl: Release 4.2.0.16.175.1027 RC on Wed Sep 06 10:27:10 2017

Copyright (c) 1982, 2017, Oracle. All rights reserved.

Connected to:
Oracle Database 11g Express Edition Release 11.2.0.2.0 - Production_

**Comment by vincentmorneau** [comment]
Right, so the error is: `Could not load file: "/usr/local/lib/node_modules/apex-nitro/node_modules/apex-publish-static-files/lib/distUpload.js"`

Can you check these paths exists for you?
- `/usr/local/lib/node_modules/apex-nitro/`
- `/usr/local/lib/node_modules/apex-nitro/node_modules/apex-publish-static-files/`
- `/usr/local/lib/node_modules/apex-nitro/node_modules/apex-publish-static-files/lib/distUpload.js`

**Comment by mgoricki** [comment]
`MG-MacBook-Pro:lib Marko$ ls /usr/local/lib/node_modules/apex-nitro/
bin		docs		lib		node_modules	readme.md
changelog.md	examples	license		package.json	test.js
MG-MacBook-Pro:lib Marko$ ls /usr/local/lib/node_modules/apex-nitro/node_modules/apex-publish-static-files/
changelog.md	docs		index.js	lib		license		package.json	readme.md	test.js
MG-MacBook-Pro:lib Marko$ ls /usr/local/lib/node_modules/apex-nitro/node_modules/apex-publish-static-files/lib/
distUpload.js	script.sql	util.js
MG-MacBook-Pro:lib Marko$ `

**Comment by vincentmorneau** [comment]
Hi Marko, did you make any progress on this?

I just tried with my new MacBook Pro and it worked the first time.

I noticed you're using an old SQLcl version (SQLcl: Release 4.2.0.16.175.1027 RC), which had problems with the script command (see https://community.oracle.com/thread/3946898)

Can you try upgrading SQLcl?

**Comment by mgoricki** [comment]
It works with SQLcl 17.2.0. You should add a note to the documentation. Thanks!
