### ISSUE TITLE
Does APEX Setup configuration Documenation needs update?

### ISSUE THREAD

**Issue by planetapex** [OraOpenSource/apex-nitro#218]
### Issue Description
First of all ,really appreciate your work. Keep up the good work, I was working using APEX Nitro a few days ago  and the configuration code was not working for me, refer to
https://github.com/OraOpenSource/apex-nitro/blob/master/docs/setup.md 
Then I used  the following code:
`declare
	l_cookie owa_cookie.cookie;
begin
	l_cookie := owa_cookie.get('oos-apex-nitro');
	if l_cookie.vals.count > 0 then
		-- Use one of the following depending on your files location
		--apex_application.g_flow_images := l_cookie.vals(1);
		-- apex_application.g_company_images := l_cookie.vals(1);
		-- apex_application.g_theme_file_prefix := l_cookie.vals(1);
		--:G_APP_IMAGES := l_cookie.vals(1);
               G_IMGS := l_cookie.vals(1);
	end if;
end;`

Also checked the headers for AJAX call and it was setting the **oos-apex-nitro** cookie value.
So does the documentation needs updating?
Should I fork the repo and post back the changes so that you can approve.

### APEX Nitro Version
v4.0.0-beta.1

### Operating System
Windows

### Node Version
v6.9.4

### Browser
v61.0.3163.100 (Official Build) (64-bit)

### APEX Version
5.0

### Web Server
ORDS 3.0.9

**Comment by vincentmorneau** [comment]
Hi,

I'm sorry that this is causing you problems. It's a documentation problem that we are working to resolve soon.

The current documentation shows the code for APEX Nitro beta 5

You downloaded beta 1, which is the default version. 

If you want, you can install the latest beta 5 by doing

```
npm install apex-nitro@4.0.0-beta.5
```

Soon APEX Nitro will be out of beta and this won't happen again.

**Comment by vincentmorneau** [comment]
Documentation should be up to date with the default release now.
