### ISSUE TITLE
babel support 

### ISSUE THREAD

**Issue by isabolic** [OraOpenSource/apex-nitro#221]
can you support babel? for modern js code :)
that would be nice :)

**Comment by vincentmorneau** [comment]
Have you tried the webpack option in the JavaScript section of your APEX Nitro project config? It includes babel, and much more.

**Comment by vincentmorneau** [comment]
You can have a look at our built in example here: https://github.com/OraOpenSource/apex-nitro/tree/master/examples/demo-webpack

You can even require npm modules and use them in the browser.

**Comment by isabolic** [comment]
tnx vincent.
