### ISSUE TITLE
owa_util.get_cgi_env('APEX-Nitro') is empty

### ISSUE THREAD

**Issue by dwarcake** [OraOpenSource/apex-nitro#223]
### Issue Description
None of the files in the dist-folder get picked up in APEX.

### APEX Nitro Version
APEX Nitro version 4.0.0

### Operating System
Windows

### Node Version
v6.11.2

### Browser
Version 61.0.3163.100 (Official Build) (64-bit)

### APEX Version
5.1.0

Since the upgrade 4.0.0-beta1 to 4.0.0 the files don't get picked up.
Made the changes as instructed in the [APEX setup doc](https://github.com/OraOpenSource/apex-nitro/blob/master/docs/setup.md) since this had to be changed.
Reason seems to be that the result of following code is empty:
owa_util.get_cgi_env('APEX-Nitro')

This makes that the Application Process doesn't execute.

Checked config and everything seems to be in order (directories, URL, etc)

**Comment by vincentmorneau** [comment]
Looks like you've done everything right. Can you provide more info on your server setup? ORDS, Tomcat, etc. I'm going to have to simulate a similar setup.

It's been working on all internal servers here. 

Is your browser pointing to localhost:4000?

Can you also please try on apex.oracle.com?

**Comment by dwarcake** [comment]
ORDS - 3.0.9.348.07.16 
Doesn't use a tomcat server at the moment ( it uses http server from Oracle Forms - Weblogic )

The browser is pointing to localhost:4000 yes.

apex.oracle.com seems to work with the same files.

Also tried making a new project pointing to the same source directory but didn't work either.

**Comment by vincentmorneau** [comment]
Do you get the notification on the top right saying "Connected to Browsersync" when your application launches?

![image](https://user-images.githubusercontent.com/5391291/32175271-d428b86c-bd5a-11e7-95b8-ada722531da8.png)

**Comment by dwarcake** [comment]
Yes, I do get the message.

If I change the condition to the statement below, it executes but I get the wrong path to my files ( since it's empty ):
owa_util.get_cgi_env('APEX-Nitro') is null

**Comment by vincentmorneau** [comment]
This https://github.com/OraOpenSource/apex-nitro/blob/master/lib/gulp/browsersync.js#L21 is what should register the HTTP header variable into your browser. 

Can you try another browser?

Also can you make sure that this: `apex-nitro -v` returns `v4.0.0` without the beta?

**Comment by dwarcake** [comment]
Ran `apex-nitro -v` which gave `APEX Nitro version 4.0.0`
Tried Mozilla Firefox and didn't work either.

Just went to visit our DBAs and they gave me an URL to test with a Tomcat server.
Apparently this fixes the problem.
Problem must be something with the Oracle HTTP server from WebLogic I guess.
All network traffic is internal so no reverse-proxies, firewalls etc. involved..
Don't really know the exact issue but it's fixed now.

I'll close the issue since Oracle HTTP server isn't included anymore anyway in WebLogic 12c.
Tomcat is the way to go.

**Comment by vincentmorneau** [comment]
Great. I'll include this somewhere in the troubleshooting doc and I'll close after. Thanks for finding a solution quickly.
