### ISSUE TITLE
Node version 8.9.X not supported yet ?

### ISSUE THREAD

**Issue by dwarcake** [OraOpenSource/apex-nitro#233]
### Issue Description
Update my node installation to the latest LTS and apex-nitro isn't working anymore.
Following error on command "apex-nitro launch <project>"

(node:14488) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Node Sass does not yet support your current environment: Windows 64-bit with Unsupported runtime (57)
For more information on which environments are supported please see:
https://github.com/sass/node-sass/releases/tag/v3.13.1
(node:14488) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

### APEX Nitro Version
v4.0.0

### Operating System
Windows 64-bit

### Node Version
v8.9.0

**Comment by vincentmorneau** [comment]
Actually it supports up to node 9. 

Sometimes when upgrading node, the node-sass package gets broken.

Can you try running this: `npm rebuild node-sass` and try again?

Reference: https://github.com/sass/node-sass/issues/1764

**Comment by vincentmorneau** [comment]
Adding this to troubleshooting documentation.

**Comment by dwarcake** [comment]
`npm rebuild node-sass` did not work but `npm rebuild -g node-sass` did work, probably because apex-nitro is installed globally ?
Thanks.

**Comment by vincentmorneau** [comment]
You are absolutely right. Thanks for checking that out.
