### ISSUE TITLE
How to troubleshooting the publishing?

### ISSUE THREAD

**Issue by rafael-trevisan** [OraOpenSource/apex-nitro#239]
Hi folks,

I've been using apex-nitro and I cannot picture myself APEXing without it! 

However, I've been having a hard time to figure out why I cannot publish my files.

I think everything is well set up. Here's the JSON for the project:

```
{
  "mode": "advanced",
  "appURL": "https://***/f?p=200",
  "srcFolder": "***\\src",
  "distFolder": "***\\dist",
  "js": {
    "processor": "default",
    "concat": false,
    "library": false,
    "tsConcat": false
  },
  "css": {
    "language": "sass",
    "concat": false
  },
  "browsersync": {
    "notify": false,
    "ghostMode": false
  },
  "header": {
    "enabled": false
  },
  "apex": {
    "openBuilder": true,
    "apexDestination": "application"
  },
  "sqlcl": {
    "path": "C:\\sqlcl\\bin\\sql",
    "connectionType": "basic",
    "username": "***",
    "password": "***",
    "host": "***",
    "port": "1521",
    "basicType": "service name",
    "serviceName": "***"
  }
}
```
When I run `apex-nitro publish project` I see in the output:

```
> is now processing your files...
> ...Done!
> Uploading to 200 - Application Static Files...
> 
> SQLcl: Release 17.4.0 Production on Fri Jan 26 13:48:05 2018
>
> Copyright (c) 1982, 2018, Oracle.  All rights reserved.
>
> Connected to:
> Oracle Database 12c Enterprise Edition Release 12.2.0.1.0 - 64bit Production
> 
> Uploading: <bunch of css>
> Uploading: <bunch of js>
> Uploading: <bunch of min>
> Uploading: <bunch of map>
>
> SQL>
> Disconnected from Oracle Database 12c Enterprise Edition Release 12.2.0.1.0 - 64bit Production
> 
> Files were uploaded successfully.
```

But none of them has been actually uploaded into my application.

Any tip how to troubleshoot this to get it working?

PS.: `apex-nitro launch project` works fine and I can see right the way any change I eventually do on my files.

Thanks in advance

**Comment by rafael-trevisan** [comment]
I forgot to mention: This behaviour isn't specific only for this application. I tried creating new and different projects but I still cannot get them published.

**Comment by rafael-trevisan** [comment]
Just a thing that came up to my mind right now: do sqlcl's username and password mean the credentials for the **schema** where the app is built or it might be my credentials (the app isn't on my schema)?

**Comment by vincentmorneau** [comment]
Hi Rafael,

The SQLcl username and password should be those of your schema. APEX Nitro uses this to log in to the schema and use the APEX API to upload all files.

In your case we are calling `wwv_flow_api.create_app_static_file`.

Please confirm you are using your schema user/password before we investigate any further.

PS: Thank you for the detailed explanation with the config file and everything. Very useful!

**Comment by rafael-trevisan** [comment]
Hey @vincentmorneau, thanks for replying.

I was actually using other credentials than the workspace one. Unfortunately, I don't have the credentials of the schema I usually work, so I guess I'll need to stick with uploading my files manually... which is not that bad if I consider all other benefits of using nitro.

Thanks again.

**Comment by vincentmorneau** [comment]
Can I quote you on Twitter? 

> I've been using apex-nitro and I cannot picture myself APEXing without it!

Do you have a Twitter handle?

**Comment by rafael-trevisan** [comment]
Sure!

Actually I’ve also cited apex-nitro in a plugin I’m getting ready to publish this week. Its webpack support allowed me to code JS easier than I thought. You did such a great job with that!

Twitter: @tr3v15

**Comment by vincentmorneau** [comment]
Rafael, I believe you have been using APEX Nitro v4.0.0. But it you were developing a plugin, what was the point of uploading the files to #APP_IMAGES#?

FYI, in the next release (v4.1.0) we have plugin support. This already works in the beta.

**Comment by rafael-trevisan** [comment]
Thanks for the heads up, @vincentmorneau! I'm indeed using v.4.0.0 but actually, I was trying to upload these files into a normal app instead of a plugin.

Looking forward to checking this v4.1.0 👍
