### ISSUE TITLE
node-sass version 3.13.1 not supported in Node.js 8.x

### ISSUE THREAD

**Issue by arinberger** [OraOpenSource/apex-nitro#244]
### Issue Description
I installed the latest version of Node.js for Windows (8.9.4 with npm version 5.6.0) and attempted to install apex-nitro according to the documentation. However, the apex-nitro installation failed because it could not find node-sass 3.13.1 at the specified location. This seems to be because Node.js 8.x does not support versions of node-sass before version 4.5.3. See [https://github.com/sass/node-sass/issues/2034](https://github.com/sass/node-sass/issues/2034) for more information. Luckily, I had an older version of Node.js (6.11.2 with npm 3.10.10) that I had previously downloaded but never installed, so I uninstalled the 8.x version and installed the 6.x version and then the apex-nitro installation worked.

### APEX Nitro Version
v4.0.0

### Operating System
Windows 10

### Node Version
v8.x

**Comment by vincentmorneau** [comment]
Hi Art,

Can you try again with the latest beta?

`npm install -g apex-nitro@4.1.0-beta.4`

We fixed a lot of compatibility issues regarding node-sass in there. It's going live (out of beta) early next week.

**Comment by arinberger** [comment]
Yes, it looks like this issue is corrected in the beta release. Here is how I tested it:

- Manually uninstalled apex-nitro
   `npm uninstall -g apex-nitro`
- Uninstalled Node.js v6.11.2
- Installed Node.js v.8.9.4
- Installed apex-nitro beta
   `npm install -g apex-nitro@4.1.0-beta.4`
- Verified successful installation by checking apex-nitro version
   `apex-nitro -v`

See attached screenshot for response. Thank you for getting back to me so quickly.

![2018-02-17_12h56_25](https://user-images.githubusercontent.com/30605452/36344031-32f1c798-13e2-11e8-8983-f5db5921fade.png)

**Comment by vincentmorneau** [comment]
Awesome! Look out for the official release soon (it should prompt from within the command line).
