### ISSUE TITLE
Automatic Heading duplicated in concatenated file

### ISSUE THREAD

**Issue by mgoricki** [OraOpenSource/apex-nitro#252]
### Issue Description
If Header and Concatenate CSS files options are enabled, comment from package.json appears in concatenated CSS file as many times as there are files and it's not removed from minified version. It's the same for JS.

### APEX Nitro Version
v4.1.0

### Operating System
macOS High Sierra

### Node Version
v6.0.0

### Project configuration screenshot
Enabled Concatenate CSS files and Header options

**Comment by vincentmorneau** [comment]
Good catch. Thanks.
