### ISSUE TITLE
CSS injection or JavaScript reload should be opt-in

### ISSUE THREAD

**Issue by vincentmorneau** [OraOpenSource/apex-nitro#258]
Feedback from John Snyder at Oracle Code Boston. Saving a file should not = page reload. This should be opt-in.

**Comment by martindsouza** [comment]
@vincentmorneau given that it's on now, I'd keep that as the default behavior. I.e. opt-out for reload on JS file save.

**Comment by vincentmorneau** [comment]
@martindsouza agreed
