### ISSUE TITLE
JavaScript not compiling when you have a function "onerror"

### ISSUE THREAD

**Issue by dwarcake** [OraOpenSource/apex-nitro#260]
### Issue Description
When we have a JavaScript function in our files called "onerror", APEX Nitro stops compiling the JavaScript files to the dist folder.

C:/Users/kmrt/AppData/Roaming/npm/node_modules/apex-nitro/node_modules/typescript/lib/lib.d.ts(19928,13): error TS2300: Duplicate identifier 'onerror'.
TypeScript error: C:/Users/kmrt/AppData/Roaming/npm/node_modules/apex-nitro/node_modules/typescript/lib/lib.d.ts(19928,13): error TS2300: Duplicate identifier 'onerror'.
TypeScript: 1 semantic error
TypeScript: emit succeeded (with errors)

When I go to the line in this file, I can see there is an "onerror" function already defined.
This seems to cause the error.
`declare var onerror: ErrorEventHandler;`

After putting // in front of it (comments) everything works fine.

Our own "onerror" function is used to catch errors from dynamic actions, it is a APEX defined function which cannot have a different name as far as I know.

### APEX Nitro Version
4.1.4

### Operating System
Windows

### Node Version
v8.9.0

### APEX Version
5.1.4

### Project configuration screenshot
Only thing worth mentioning is that we use TypeScript as JavaScrip processor.

**Comment by vincentmorneau** [comment]
Thanks for filling this.

I added this line to my typescript test file:
```
declare var onerror: ErrorEventHandler;
```

And it works fine. Is it possible that you would have a conflicting declaration in an other file?

I'm not the typescript expert so I'll have to learn this a little.

**Comment by dwarcake** [comment]
Our javascript file contains something like this:
`function onerror(p_message){
    // Print message
    console.log(p_message);
}`

Its just plain JavaScript, but because we use ES6 notation in our other functions, we set our JavaScript processing in APEX Nitro to TypeScript.
We want to move to TypeScript in the future but this is not yet the case.

**Comment by vincentmorneau** [comment]
I'm still confused. Do you use both JavaScript & TypeScript at the same time? Can you explain the structure of your src folder and indicate which file(s) has these `onerror` references?

**Comment by vincentmorneau** [comment]
Got it. Will try again later. FYI I had tested with this use case:
```
/src/
       /ts/
           files.ts <- here is the onerror function
       /scss/
       /img/

```

**Comment by vincentmorneau** [comment]
@dwarcake OK so I was finally able to reproduce.

I think it's a typescript issue so I won't dive into it, but you can rewrite it like this:

```js
var onerror = function (p_message) {
	// Print message console.log(p_message);
}
```

and it works fine, and does the same thing.

**Comment by dwarcake** [comment]
Can confirm this solves the compile issue.
Thank you for your help.
