### ISSUE TITLE
Strange behavior with iFrames

### ISSUE THREAD

**Issue by rafael-trevisan** [OraOpenSource/apex-nitro#261]
### Issue Description
I've been having a very strange behaviour when using Nitro within an app which has few iframes. It's kind of hard to explain as the app behaves strangely in many aspects. I made a GIF though with Nitro and without it. Hope it helps.

PS.: each "tabular form" is sitting on a different page and they're all put together using iframes, like this:

```
<iframe id="iframe-addresses" src="f?p=&APP_ID.:60:&APP_SESSION.:" frameborder="0" scrolling="no" onload="resizeMe(this);" class="margin-bottom-md"></iframe>
<iframe id="iframe-phones"    src="f?p=&APP_ID.:70:&APP_SESSION.:" frameborder="0" scrolling="no" onload="resizeMe(this);" class="margin-bottom-md"></iframe>
<iframe id="iframe-online"    src="f?p=&APP_ID.:80:&APP_SESSION.:" frameborder="0" scrolling="no" onload="resizeMe(this);"></iframe>
```

### APEX Nitro Version
v4.0.0 - v.4.1.4

### Operating System
Windows

### Node Version
v8.1.2

### Browser
Chrome v66

### APEX Version
v5.1.1

### Project configuration screenshot
Without Nitro
![wo-nitro](https://user-images.githubusercontent.com/17282530/40498839-fb2f3b30-5f34-11e8-9c79-41a28f26d7ac.gif)

With Nitro
![w-nitro](https://user-images.githubusercontent.com/17282530/40498858-098c5b18-5f35-11e8-9274-c60b6bc3a831.gif)

Here is the config for this project.
```
{
  "mode": "advanced",
  "appURL": "***",
  "srcFolder": "***\\src",
  "distFolder": "***\\dist",
  "js": {
    "processor": "default",
    "concat": false,
    "entries": ["***\\src\\js\\app.js", "***\\src\\js\\p50.js", "***\\src\\js\\p90.js"],
    "bundleFilename": "***.bundle",
    "library": false,
    "tsConcat": false
  },
  "css": {
    "language": "sass",
    "concat": false
  },
  "browsersync": {
    "realTime": true,
    "ghostMode": true,
    "notify": true
  },
  "header": {
    "enabled": false
  },
  "apex": {
    "openBuilder": true
  },
  "publish": {
    "destination": "application"
  }
}
```

**Comment by vincentmorneau** [comment]
Can you disable `ghostMode ` I think it's messing up with your iframes as it tries to replicate the click / scroll / typing in all iframes at once.

![image](https://user-images.githubusercontent.com/5391291/40502458-086cb588-5f59-11e8-8014-13fc2d32c1a7.png)

**Comment by rafael-trevisan** [comment]
👍 worked like magic lol
