### ISSUE TITLE
Error: Unhandled "error" event. ([object Object]) at Gulp.emit (events.js:185:19)

### ISSUE THREAD

**Issue by rafael-trevisan** [OraOpenSource/apex-nitro#262]
### Issue Description
I'm getting an unhandled error when using webpack

### APEX Nitro Version
APEX Nitro version 4.1.4

### Operating System
Windows

### Node Version
v8.11.2

### NPM Version
6.1.0

### Browser
Chrome v66

### APEX Version
v5.1.1

```
is compiling *** ...
C:\Users\Rafael\AppData\Roaming\npm\node_modules\apex-nitro\node_modules\async-done\index.js:18
    throw err;
    ^

Error: Unhandled "error" event. ([object Object])
    at Gulp.emit (events.js:185:19)
    at Object.error (C:\Users\Rafael\AppData\Roaming\npm\node_modules\apex-nitro\node_modules\undertaker\lib\helpers\createExtensions.js:61:10)
    at handler (C:\Users\Rafael\AppData\Roaming\npm\node_modules\apex-nitro\node_modules\now-and-later\lib\map.js:46:14)
    at f (C:\Users\Rafael\AppData\Roaming\npm\node_modules\apex-nitro\node_modules\once\once.js:25:25)
    at f (C:\Users\Rafael\AppData\Roaming\npm\node_modules\apex-nitro\node_modules\once\once.js:25:25)
    at tryCatch (C:\Users\Rafael\AppData\Roaming\npm\node_modules\apex-nitro\node_modules\async-done\index.js:24:15)
    at done (C:\Users\Rafael\AppData\Roaming\npm\node_modules\apex-nitro\node_modules\async-done\index.js:40:12)
    at Domain.onError (C:\Users\Rafael\AppData\Roaming\npm\node_modules\apex-nitro\node_modules\async-done\index.js:51:5)
    at Object.onceWrapper (events.js:316:30)
    at emitOne (events.js:115:13)
    at Domain.emit (events.js:210:7)
    at Domain._errorHandler (domain.js:118:23)
    at process._fatalException (bootstrap_node.js:326:33)
```

```
{
  "mode": "advanced",
  "appURL": "***",
  "srcFolder": "C:\\***\\src",
  "distFolder": "C:\\***\\dist",
  "js": {
    "processor": "webpack",
    "concat": false,
    "entries": ["C:\\***\\src\\js\\app.js"],
    "bundleFilename": "bundle",
    "library": true,
    "libraryName": "app",
    "tsConcat": false
  },
  "css": {
    "language": "sass",
    "concat": false
  },
  "browsersync": {
    "realTime": true,
    "ghostMode": false,
    "notify": true
  },
  "header": {
    "enabled": false
  },
  "apex": {
    "openBuilder": false
  },
  "publish": {
    "destination": "application"
  }
}
```

**Comment by vincentmorneau** [comment]
Hi Rafael, thanks for another great issue description.

One thing APEX Nitro needs to improve is providing better error messages. Haven't found a proper way yet. Any idea is welcome.

To get back on your issue, I know you were able to use the webpack option before, so what changed? Are you able to locate a particular piece of code that triggers the crash?

**Comment by rafael-trevisan** [comment]
Hey @vincentmorneau, you're welcome. I know how hard is to figure out when someone just says "It isn't working" :-)

Indeed I was able to use webpack. Thing is: I cannot recall where I did (yeah, building a bunch of apps recently) so I couldn't check that out.

This issue has been related to a new app, created from scratch and actually I don't have any JS code other than some `console.info('test');`

I've installed some previous versions of Nitro (until back to 4.0.0) but it didn't help. I'm sure I got this working before.

I'll try to replicate on apex.oracle.com and in the meantime, if you need any additional log or information, just let me know.

Cheers

**Comment by rafael-trevisan** [comment]
In case it helps:

**v4.0.0-beta.1** -> works nicely.
**v4.0.0-beta.2** -> TypeError: Cannot read property 'toLowerCase' of undefined
**v4.0.0-beta.3** -> TypeError: Cannot read property 'toLowerCase' of undefined
**v4.0.0-beta.4** -> TypeError: Cannot read property 'toLowerCase' of undefined
**v4.0.0-beta.5** -> Error: original.line and original.column are not numbers -- you probably meant to omit the original mapping entirely and only map the generated position. If so, pass null for the original mapping instead of an object with empty or null values.
**v4.0.0** -> Error: original.line and original.column are not numbers -- you probably meant to omit the original mapping entirely and only map the generated position. If so, pass null for the original mapping instead of an object with empty or null values.
**v4.1.0** -> Error: Unhandled "error" event. ([object Object])

Then the same error repeats until **v4.1.4**
