### ISSUE TITLE
APEX Files Destination can be server folder ?

### ISSUE THREAD

**Issue by mahi2net** [OraOpenSource/apex-nitro#263]
### Issue Description
[Explain]
I am keeping all custom css files are in apache root folder making cache , header expiry etc. 
In apex nitro, Publish Files is only allowing to application,workspace, theme & plugin. If I can add the local server root path, it will save my time.
### APEX Nitro Version
[Example: v4.0.0]

### Operating System
[Example: Windows]

### Node Version
[Example: v6.9.1]

### Browser
[Example: Chrome v50]

### APEX Version
[Example: v5.1.1]

### Web Server
[Example: ORDS 3.0.9, Tomcat 7]

### Project configuration screenshot
[Paste image]

**Comment by vincentmorneau** [comment]
That's a great idea. I would need to look into some kind of SFTP module from npm to integrate that into APEX Nitro.

In the meantime, you can zip the `dist` folder and upload it manually to your server.

I'll flag this as a new feature for future release.

**Comment by mahi2net** [comment]
Thanks vincent.

**Comment by mahi2net** [comment]
1) can I add network path in to source folder & distributable folder & also
package.json path ?

2) If there has an option to include apex lib files while concatenating ,
we can use this final file in to concatenated files section in user
interface.

**Comment by vincentmorneau** [comment]
1- Haven't tried, but it should work, please let me know the result.
2- You could download the APEX libs and add them to your source folder, although I don't see the point as they would be injected twice into the app.

**Comment by mahi2net** [comment]
If we are adding concatenated file in to “concatenated files” region in to
user interface , it will not inject lib files that os defined into there

**Comment by vincentmorneau** [comment]
Started looking into this and I feel this is out of scope. There are too many server configurations, ftp, sftp and I'm afraid we would be going down a rabbit hole to reproduce what other tools do just fine.

After all, this process should not happen often so I'm happy with documenting copy paste the dist folder into the web server manually
