### ISSUE TITLE
Basic config should sync files

### ISSUE THREAD

**Issue by vincentmorneau** [OraOpenSource/apex-nitro#264]
Basic config should sync files. Right now it does not.

**Comment by sypulabartosz** [comment]
Using advanced config apex nitro I think it is not sync files as well. The apex nitro is reacting on changes in files, the page is reloading, but there is no effect on apex page.

**Comment by mahmoudrabie** [comment]
Hi Vincent 
Advanced configuration doesn't sync also

**Comment by rafael-trevisan** [comment]
Are you using any VPN to access APEX?

**Comment by sypulabartosz** [comment]
At the beginning I faced some problems with sync in Apex Nitro because I tested it on the application in which wasn't used ords.
But when I installed ords sync was working correcttly in advanced mode.

**Comment by vincentmorneau** [comment]
@mahmoudrabie Would you care to elaborate a little? Advanced config should auto sync.

**Comment by mahmoudrabie** [comment]
Thanks a lot, it is working fine now.
