### ISSUE TITLE
APEX 18.1 issue with generated icon

### ISSUE THREAD

**Issue by vincentmorneau** [OraOpenSource/apex-nitro#265]
APEX 18.1 generates an icon in the Shared Components (App static files) so when you setup APEX Nitro at first, it causes a conflict.

Not sure if there's a way around that, except documentation, but it's worth investigating the options.

**Comment by MaikMichel** [comment]
What about downloading app-icon.css and app-icon.svg to configured src-directory. I placed them manually in that directory and it worked...

**Comment by vincentmorneau** [comment]
Follow-up: the next release of APEX might take app-icon.css and app-icon.svg out of the shared components, so we wouldn't have this problem anymore.

In the meantime, I will document the workaround.
