### ISSUE TITLE
Clarify configuration difference between App and Plugin

### ISSUE THREAD

**Issue by zhudock** [OraOpenSource/apex-nitro#270]
I'm attempting to use APEX-Nitro to speed up plugin development. 

Based on the setup documentation, I assumed in my Application Process I should use the PL/SQL below

```
apex_application.g_flow_images := owa_util.get_cgi_env('APEX-Nitro');
:G_APEX_NITRO_IMAGES := owa_util.get_cgi_env('APEX-Nitro');
```

However, APEX was no longer able to see the Jet libraries after that. Based on your KScope18 slides, I changed the PL/SQL to ONLY set G_APEX_NITRO_IMAGES, and all seems to be acting as expected now.
```
--apex_application.g_flow_images := owa_util.get_cgi_env('APEX-Nitro');
:G_APEX_NITRO_IMAGES := owa_util.get_cgi_env('APEX-Nitro');
```

**Comment by vincentmorneau** [comment]
@zhudock I'm sorry for the confusion. I think the [documentation here](https://github.com/OraOpenSource/apex-nitro/blob/master/docs/setup.md#apex-plugin-development) mentions clearly that only `:G_APEX_NITRO_IMAGES := owa_util.get_cgi_env('APEX-Nitro');` should be used for plugin development.

I'll close this for now, but feel free to re-open and suggest a clearer documentation.

**Comment by zhudock** [comment]
I think the confusion is that the first example Application Process source [here](https://github.com/OraOpenSource/apex-nitro/blob/master/docs/setup.md#application-process) includes 4 lines, 3 of which are commented out. The fact that they are all included could be interpreted as being entirely valid to include all 4 of them active at once. Perhaps the first example could change, or the plugin-specific directions could be updated to say something similar to:

> Replace `apex_application.g_flow_images := owa_util.get_cgi_env('APEX-Nitro');` in Application Process source (see above) with `:G_APEX_NITRO_IMAGES := owa_util.get_cgi_env('APEX-Nitro');`
