### ISSUE TITLE
npm WARN ajv-keywords@3.2.0 requires a peer of ajv@^6.0.0 but none is installed. You must install peer dependencies yourself

### ISSUE THREAD

**Issue by mahmoudrabie** [OraOpenSource/apex-nitro#271]
### Issue Description
$ npm install -g apex-nitro
/usr/local/bin/apex-nitro -> /usr/local/lib/node_modules/apex-nitro/bin/apex-nitro.js
npm WARN ajv-keywords@3.2.0 requires a peer of ajv@^6.0.0 but none is installed. You must install peer dependencies yourself.

+ apex-nitro@4.1.5
updated 1 package in 54.991s

### APEX Nitro Version
$ apex-nitro -v
APEX Nitro version 4.1.5

### Operating System
macOS High Sierra Version 10.13.4

### Node Version
$ node -v
v8.9.4

### Browser
Google Chrome is up to date
Version 67.0.3396.99 (Official Build) (64-bit)

### APEX Version
Application Express 18.1.0.00.45

### Web Server
Oracle REST Data Services 18.1.1

### Project configuration screenshot
{
    "mode": "advanced",
    "appURL": "myappurl",
    "srcFolder": "mysrcurl",
    "distFolder": "mydisturl",
    "js": {
        "processor": "default",
        "concat": false,
        "library": false,
        "tsConcat": false
    },
    "css": {
        "language": "css",
        "concat": false
    },
    "browsersync": {
        "realTime": true,
        "ghostMode": true,
        "notify": true
    },
    "apex": {
        "openBuilder": true
    },
    "publish": {
        "destination": "theme",
        "path": "sqlcl_path",
        "connectionType": "custom",
        "connectionString": "schema/password@//server:1521/sid"
    }
}

**Comment by vincentmorneau** [comment]
Thanks for creating an issue. This is a warning that I'd like to suppress during the installation, but it's not possible at the moment. It is normal and does not affect APEX Nitro's features.

I'll add a note to the doc.
