### ISSUE TITLE
How to call a JavaScript function using webpack but without exposing as a library?

### ISSUE THREAD

**Issue by rafael-trevisan** [OraOpenSource/apex-nitro#274]
Hi,

This is not actually an issue, it's just a question.

Scenario: APEX Nitro with webpack without "Expose as a library".

How should I call a JavaScript function, sitting in app.js, for i.e., from my page in APEX?

**Comment by vincentmorneau** [comment]
My understanding is that wouldn't be possible. This scenario would apply for internal (hidden) JS processing.

You bring a good point though. Is there any use for `APEX Nitro with webpack without "Expose as a library".` in an APEX context? If not, I would suggest to remove "Expose as a library" from the config and make it the default behaviour.
