### ISSUE TITLE
Do we need to conform to a strict folder structure?

### ISSUE THREAD

**Issue by tschf** [OraOpenSource/apex-nitro#275]
### Issue Description

For the source code, all your examples use the folder structure:

```
src/
  js/
    *.js
  css/
    *.css
```

Just confirming, that we need to conform to this folder structure to use apex-nitro? 

Specifically, JavaScript code needs to be in the root source folder

A couple of scenarios:

1. Have scripts in the root source folder - may not be best practice, I acknowledge
2. If I'm using typescript, I'm not sure placing them in folder js makes sense (or maybe since it transpiles into JS, it does?)
3. Using some other folder name other than js
4. For large libraries, I create more folder nesting, e.g:

```
C:\Users\trent\Projects\awesome-proj>tree
C:.
├───dist
└───source
    └───module1
        └───js
```

In all these examples, source compilation doesn't work. It simply copies the source file into the dist folder, using the sample path that is in the source folder.

Should be an option to use other folder naming? Or if you want users to use js,css folders in the root source folder, at least my last example is a valid one?

Further, I also tried this:

```
├───dist
└───source
    └───js
        └───module1
```

And nothing was generated in dist.

### APEX Nitro Version
4.1.5

### Operating System
Windows

### Node Version
6.10.3

### Browser
Firefox 62

### APEX Version
18.1

### Web Server
apex.oracle.com 

### Project configuration
```json
{
  "mode": "advanced",
  "appURL": "https://apex.oracle.com/pls/apex/f?p=45358",
  "srcFolder": "C:\\Users\\trent\\Projects\\awesome-proj\\source",
  "distFolder": "C:\\Users\\trent\\Projects\\awesome-proj\\dist",
  "js": {
    "processor": "default",
    "concat": true,
    "concatFilename": "app",
    "library": false,
    "tsConcat": true,
    "tsConcatFilename": "app"
  },
  "css": {
    "language": "css",
    "concat": false
  },
  "browsersync": {
    "realTime": false,
    "ghostMode": false,
    "notify": false
  },
  "header": {
    "enabled": false
  },
  "apex": {
    "openBuilder": false
  },
  "publish": {
    "destination": "application"
  }
}
```

**Comment by fuzziebrain** [comment]
Thanks @tschf , it should take care of nesting. I'll have a look and suggest a fix later.

**Comment by tschf** [comment]
Just checking things again. The last example:
```
src/
  js/
    module1/
       *.js
```
Does seem to work.

**Comment by vincentmorneau** [comment]
> Just confirming, that we need to conform to this folder structure to use apex-nitro?

Yes. Only folders named `js`, `css`, `scss`, `less` will be subject to file processing (file minification, concat, etc). 

Then within those folders you can have as many levels as you want.

Other folder names will simply be copied to your `dist` folder.

> Specifically, JavaScript code needs to be in the root source folder

No. Anywhere in the `src/js/*/*/*/*`

> Should be an option to use other folder naming?

I want to avoid that. Would make the config too complicated for the typical user. You can create and launch two APEX Nitro projects for a single APEX app and use different configs too.

---

Any suggestion on improving the documentation about that topic?

**Comment by tschf** [comment]
> Any suggestion on improving the documentation about that topic?

In your main README.md document there is a system requirements section (https://github.com/OraOpenSource/apex-nitro#system-requirements). I think it best fits into here?
