### ISSUE TITLE
Use apex-nitro to employ React-Native as a wrapping layer over APEX

### ISSUE THREAD

**Issue by mahmoudrabie** [OraOpenSource/apex-nitro#278]
Hello apex-nitro Team,

Thanks a lot for your support.

React-Native (RN) is one of the most advanced mobile development frameworks. Is there a way to use apex-nitro to employ RN as a front-end or a wrapping layer over APEX.

Regards
Mahmoud

**Comment by vincentmorneau** [comment]
Hi @mahmoudrabie,

You should look into the webpack option of the JavaScript. Then you can import npm modules like react-native. Example:  

https://github.com/OraOpenSource/apex-nitro/tree/master/examples/demo-webpack

In this example we are showing how to use `lodash` as an npm module. importing react-native would be similar.

**Comment by mahmoudrabie** [comment]
Excellent 

Could I do the same for Angular ?

**Comment by vincentmorneau** [comment]
@mahmoudrabie any npm package

**Comment by mahmoudrabie** [comment]
Thanks a lot
