### ISSUE TITLE
How configure tsconfig?

### ISSUE THREAD

**Issue by kopsondropson** [OraOpenSource/apex-nitro#281]
### Issue Description
I'm facing an issue with Apex Nitro and TypeScript configuration to add orclapex-js typings. While Apex Nitro launch my project and tsc starts compile the fallowing error occured:

```
src\js\diagramManager.ts(18,16): error TS2304: Cannot find name 'apex'.
TypeScript error: src\js\diagramManager.ts(18,16): error TS2304: Cannot find name 'apex'.
TypeScript: 1 semantic error
```

I'v got tsconfig.json at the root of my project folder structure. It seems like Apex Nitro ignore tsconfig.json. When I try to compile project via tsc manually the problem is gone.

tsconfig.json
```
{
    "compilerOptions": {
        "module": "commonjs",
        "lib": [
            "es6",
            "dom"
        ],
        "target": "es5",
        "types": [
            "orclapex-js"
        ],
        "moduleResolution": "node",
        "removeComments": true
    }
}
```
Apex Nitro project config
```
{
        "mode": "advanced",
        "srcFolder": "C:\\Users\\Damian\\Documents\\Projekty\\project\\src",
        "distFolder": "C:\\Users\\Damian\\Documents\\Projekty\\project\\dist",
        "js": {
            "processor": "typescript",
            "concat": false,
            "library": false,
            "tsConcat": true,
            "tsConcatFilename": "app"
        },
        "css": {
            "language": "css",
            "concat": false
        },
        "browsersync": {
            "realTime": true,
            "ghostMode": false,
            "notify": false
        },
        "header": {
            "enabled": false
        }
```
### APEX Nitro Version
v4.1.5

### Node Version
v8.9.1

### Project configuration screenshot
![image](https://user-images.githubusercontent.com/32899213/43550022-9dff5bea-95e2-11e8-870e-70c3d82cfabd.png)

**Comment by vincentmorneau** [comment]
I understand your problem.

Would it help if we added a new configurable field in the APEX Nitro config for the path of your tsconfig.json? Then APEX Nitro could localize it and load it properly. Otherwise there is no way to know where you put it.

**Comment by vincentmorneau** [comment]
@rafael-trevisan I like your idea. The only problem I see is that the package.json reference is currently hidden under there:

![image](https://user-images.githubusercontent.com/5391291/43581210-28c100e2-9626-11e8-9726-e952b0078c4f.png)

It would not be very intuitive to activate the Header section to enable the tsconfig.

Back in the early days of APEX Nitro, there was no config UI. We had a file similar to package.json containing all of APEX Nitro parameters (`apexnitro.json`).

Any other suggestion is welcome.

**Comment by rafael-trevisan** [comment]
Yeah, that indeed wouldn't be very intuitive.

👍 for having an extra configurable field then

**Comment by vincentmorneau** [comment]
Closing because the TypeScript approach will change dramatically in APEX Nitro v5
