### ISSUE TITLE
Local files are never referenced in APEX app.

### ISSUE THREAD

**Issue by mcgeemp** [OraOpenSource/apex-nitro#282]
### Issue Description
Hello, I have gotten where I can config/launch a project, Nitro recognizes file changes and pushes them to the browser.  The browsers refreshes on javascript updates and I am able to successfully sync with other devices.  The notification in the task bar even indicates the CSS/JS changes are successfully being pushed.  The issue is, I can't seem to get the files to actually reference live, meaning if I have test.js and test.css, the files aren't called/referenced on the page and thus never used.  I have exposed the value of apex_application.g_flow_images: as "//localhost:4000/".

I've inspected elements and have yet to see these files called. In addition, I have **never** seen the notification on the top right saying "Connected to Browsersync".

### APEX Nitro Version
v4.1.5

### Operating System
Win 7

### Node Version
v8.11.3

### Browser
Firefox

### APEX Version
18.1

### Web Server
apex.oracle.com

### Project configuration screenshot

{
    "mode": "advanced",
    "appURL": "https://apex.oracle.com/pls/apex/f?p=130876",
    "srcFolder": "/Users/mmcgee/Desktop/Matt/apexresources/McGeek/src",
    "distFolder": "/Users/mmcgee/Desktop/Matt/apexresources/McGeek/dist",
    "js": {
        "processor": "default",
        "concat": false,
        "library": false,
        "tsConcat": false
    },
    "css": {
        "language": "css",
        "concat": false
    },
    "browsersync": {
        "realTime": true,
        "ghostMode": true,
        "notify": true
    },
    "header": {
        "enabled": false
    },
    "apex": {
        "openBuilder": true
    },
    "publish": {
        "destination": "application"
    }
`

**Comment by rafael-trevisan** [comment]
Hi @mcgeemp,

If I understood your issue you need to include a reference to your files.

Have a look here: https://github.com/OraOpenSource/apex-nitro/blob/master/docs/setup.md#references

Or just add #APP_IMAGE#css/test.css to your page and you should see these files referenced 😉

**Comment by mcgeemp** [comment]
Thanks @rafael-trevisan , that does work and will get me going.  Only reason I didn't do that was I was a KSCOPE and saw Vincent present, which I believe included he adding files locally on the fly and it picking them up without having to do this, but I'll stick with this method for the time being.

**Comment by rafael-trevisan** [comment]
You're welcome!

After referencing your "main" files you may achieve what you're looking for.

Let's say you're using SCSS and you've already referenced your `app.css` within your application, then you create a new `_new_file.scss` file and import it into your `app.scss`. At this moment you'll see it reflecting in your app right away without having to reference the new file in APEX.

The same for JS if you're using webpack, for i.e., and use export/import modules.

Got it?

**Comment by vincentmorneau** [comment]
@mcgeemp Rafael is correct. The reference to `#APP_IMAGE#css/test.css` has to be done once when you start building your app. With file concatenation enabled, you will not have to revisit this step in the future.

Any recommendation for improving the documentation?
