### ISSUE TITLE
Too many errors

### ISSUE THREAD

**Issue by kopsondropson** [OraOpenSource/apex-nitro#283]
### Issue Description
When I write code with ES6 syntax (let, arrow func, template strings etc.) I've got warnings from APEX Nitro about ES6 compatibility. That's ok, but when I've got 50 or more warnings **per file** then APEX Nitro stop scanning my project and throws an error **"Too manu errors. (X% scanned)"**. I lost some time to figure out that the problem is not in my code, but in compiler itself which accepts only 49 warnings... Below I put a sample solution when I changed **let** to **var**. The same behavior of APEX Nitro is when I change arrow functions with ES5 function syntax, template strings with string concatenations etc.

### APEX Nitro Version
v4.1.5

### Node Version
v8.11.3

### Screenshots
Situation when APEX Nitro has 50 warnings and throws an "Too many errors." error. Pay attention to last warning about **let** keyword.
![image](https://user-images.githubusercontent.com/32899213/43944922-e88df398-9c80-11e8-8589-6d2ab9dc91fd.png)

Fixing problem with replacing **let** keyword to **var**. The last error is gone and the hole project compile correctly.
![image](https://user-images.githubusercontent.com/32899213/43945048-4b13c6dc-9c81-11e8-8657-db8dfd034aec.png)

**Comment by mgoricki** [comment]
Yesterday I've noticed that when I use ES6 minified version of a JS file is not generated or refreshed.

I'm also using APEX Nitro 4.1.5

Br,
Marko

**Comment by dwarcake** [comment]
In the config under "JavaScript" you can choose "TypeScript".
This will allow you to write in ES6 syntax.

You don't have to write TypeScript.
Just keep using the "js" folder and ES6-JavaScript and it will compile without errors on the syntax.

That's how I use it in our project and it works fine.

**Comment by kopsondropson** [comment]
The problem is I use **js** folder :laughing:

**Comment by kopsondropson** [comment]
Is there any option to disable these warnings ?

**Comment by vincentmorneau** [comment]
Hi Damian, I won't have access to a computer until next week (vacation),
but there is a good reason to keep these warnings. These es6 syntax aren't
compatible with all current browsers yet. APEX still supports IE11 so APEX
Nitro does as well.

As Kim mentioned, you can toggle to a typescript processing in your APEX
Nitro config, and use ES6 and it'll be converted to es5 when compiling the
project. What do you mean you are using the js folder? That should be fine
nonetheless.

**Comment by vincentmorneau** [comment]
I see. I will see what I can do. Thanks
