### ISSUE TITLE
Steps to Oracle JET support to APEX App using apex-nitro

### ISSUE THREAD

**Issue by mahmoudrabie** [OraOpenSource/apex-nitro#286]
Hi Vincent

I hope you are fine

I was wondering what are steps Oracle JET support to APEX using apex-nitro?
https://docs.oracle.com/en/middleware/jet/5.2/develop/prerequisites-developing-applications-oracle-jet.html#GUID-ABE2373F-287F-4C3A-BEBD-02F179F399FD

Regards
Mahmoud

**Comment by vincentmorneau** [comment]
Hi Mahmoud,

Can you just include JET in a `/lib/` subfolder within your APEX Nitro source folder?

What are you trying to accomplish?

**Comment by mahmoudrabie** [comment]
I am trying to build a dashboard UI using Oracle JET

**Comment by mahmoudrabie** [comment]
Thanks again.

But how to install npm dependencies. 

Please look at this prerequisite
https://docs.oracle.com/en/middleware/jet/5.2/develop/prerequisites-developing-applications-oracle-jet.html#GUID-6AEB5A00-22D8-4BC1-AAB3-4134F906C1C0

**Comment by vincentmorneau** [comment]
I don't think this is the best approach for APEX development. Try including the JET distribution files in APEX directly: https://docs.oracle.com/database/apex-18.1/HTMDB/Understanding-Oracle-JET-Integration-with-Oracle-Application-Express.htm#HTMDB-GUID-FD5B3839-EBB2-4C5C-984F-4C90BE46684B
