### ISSUE TITLE
[DEP0097] DeprecationWarning

### ISSUE THREAD

**Issue by rafael-trevisan** [OraOpenSource/apex-nitro#293]
Hi all,

Is anyone else getting this message when running Nitro on Mac?

```
is compiling app ...
(node:11234) [DEP0097] DeprecationWarning: Using a domain property in MakeCallback is deprecated. Use the async_context variant of MakeCallback or the AsyncResource class instead.
...Done!
...Now launching!

```

Node v10.14.2
npm 6.5.0
APEX Nitro version 4.1.6

**Comment by vincentmorneau** [comment]
That would be a warning specific to your code, not APEX Nitro on Mac. Can you try putting the whole file in comment to see if the warning disappears?

**Comment by rafael-trevisan** [comment]
Thx @vincentmorneau, I didn't have a chance to review the code yet as it's importing a lot of modules, but I'll definitely do it.
