### ISSUE TITLE
How to integrate Angular 7 into Oracle Apex using apex-nitro

### ISSUE THREAD

**Issue by mahmoudrabie** [OraOpenSource/apex-nitro#294]
### Issue Description
Oracle APEX 18.2 is the best RAD framework offered by Oracle for building database based application. Angular 7 is the top front-end development framework provided by Google. Could we incorporate both giants in the same solution stack using apex-nitro?

### APEX Nitro Version
Latest

### Operating System
Mac OS High Sierra

### Node Version
v6.7.1

### Browser
Chrome v50

### APEX Version
v18.2

### Web Server
ORDS 3.0.9

**Comment by vincentmorneau** [comment]
You can totally do Angular within APEX Nitro. Just include the Angular CDN within your APEX app and you should be able to use the library within Nitro. Let me know if you were thinking of something more integrated.

**Comment by mahmoudrabie** [comment]
Dear Vincent 

Thanks a lot for your response.

I don’t want to use CDN way.

I want step-by-step guide to integrate using webpage for example or anything recommended for best performance.

In addition, I am planning to use Angular+PWA+APEX

Kind Regards
Mahmoud

**Comment by vincentmorneau** [comment]
That would be a great idea for a blog post series. I am planning on doing one with React later this year, but not Angular.

**Comment by mahmoudrabie** [comment]
OK my friend

I will try to do it with Angular In my blog post.

In parallel , I will be Waiting for your React.

Thanks again

**Comment by wiktusser** [comment]
> That would be a great idea for a blog post series. I am planning on doing one with React later this year, but not Angular.

Hi @vincentmorneau, soon I will need to start research this topic in order to incorporate react to APEX. Just wondering if you are still planning to post something about it? Maybe you already have some tutorials that you can share?

@mahmoudrabie how was it? Have you faced any issues or blockers for that?

Thanks both!

**Comment by vincentmorneau** [comment]
@wiktusser I have done conferences and a webinar on React and APEX. You can probably find a recording on Insum's youtube channel.
