### ISSUE TITLE
Handling password in apexnitro.config.json

### ISSUE THREAD

**Issue by vincentmorneau** [OraOpenSource/apex-nitro#297]
Our new config mechanism will use files at the project directory (`apexnitro.config.json`)

How should we go about handling passwords under `publish.password`?
Should it be a path to a separate file which is ignored by version control?
Should it be a path to a separate file that contains the whole connection string?

**Comment by rafael-trevisan** [comment]
Hey @vincentmorneau, usually I go with a specific git ignored file with the credentials only.

**Comment by vincentmorneau** [comment]
Nice, I was thinking along those lines too. Does you file contain the password only or the whole connection string?

**Comment by rafael-trevisan** [comment]
Only username and password.

The connection string I like to keep track in a git controlled file.

**Comment by vincentmorneau** [comment]
That makes sense. Thanks for the insight.
