### ISSUE TITLE
How to setup Material Apex with Apex Nitro ? 

### ISSUE THREAD

**Issue by maximeperezpro** [OraOpenSource/apex-nitro#299]
### Issue Description
[Explain]

### APEX Nitro Version
[Example: v4.0.0]

### Operating System
[Example: Windows]

### Node Version
[Example: v6.9.1]

### Browser
[Example: Chrome v50]

### APEX Version
[Example: v5.1.1]

### Web Server
[Example: ORDS 3.0.9, Tomcat 7]

### Project configuration screenshot
[Paste image]

**Comment by maximeperezpro** [comment]
When I run Apex Nitro, my browser launch local application. I would like start the dev 
environment. 

My Apex-Nitro it's well configured, because it's work without material apex...

Thanks in advance,

**Comment by vincentmorneau** [comment]
As indicated in your email, is this resolved?

**Comment by maximeperezpro** [comment]
Yes

Le jeu. 23 mai 2019 à 14:33, Vincent Morneau <notifications@github.com> a
écrit :
