### ISSUE TITLE
transpling / babel

### ISSUE THREAD

**Issue by apps4u** [OraOpenSource/apex-nitro#300]
### Issue Description
I would like write my code using es6 standard but have it compiled down to es5.
Now I know how to do this in js project but not with apex-nitro .
So my question is how I could do this or would it require me to edit apex-nitro myself.

### APEX Nitro Version
[Example: v4.0.0]

### Operating System
MAC OS X 10.14.5

### Node Version
v6.9.1

### Browser
CHROME 74

### APEX Version
APEX Nitro version 4.1.6

### Web Server
ORDS 18, Tomcat 7

### Project configuration screenshot

<img width="1448" alt="Screen Shot 2019-05-28 at 3 36 20 pm" src="https://user-images.githubusercontent.com/756522/58453422-6604a480-815e-11e9-8900-c9686188963f.png">

**Comment by vincentmorneau** [comment]
That is a great question and it is the focus of APEX Nitro v5 (next release).

I am hoping to release sometime during the summer.

**Comment by apps4u** [comment]
Cool, I'm happy to help if I can I'll see if I can get the edit i did to work , I got it half working but some of the test failed and when added babel before the pipe to gulp-uglyfly , Now when I did I started getting Module export errors. I only spent like a half hour on it. So next question before I do look at adding it will you accept pull request (if working and tested).

**Comment by apps4u** [comment]
All Cool. Il’l look a the current issues and see if I can help thanks.
