### ISSUE TITLE
JavaScript Initialization Code

### ISSUE THREAD

**Issue by rafael-trevisan** [OraOpenSource/apex-nitro#302]
Hi folks,

Would you know if we can reference an external file in the "JavaScript Initialization Code" setting in APEX?

We have this setting in Page Items and Regions and I was wondering if we could use Nitro to change a JS code that would be "injected" in this field setting.

Thx!

**Comment by vincentmorneau** [comment]
Of course you can define a function in your files (using APEX Nitro) and then reference that function in  "JavaScript Initialization Code" setting in APEX.
