### ISSUE TITLE
Warning each time I deploy

### ISSUE THREAD

**Issue by apps4u** [OraOpenSource/apex-nitro#307]
### Issue Description
Ive started to get a issue as of yesterday I did a update on my npm -g modules and now I get a warning each time I build.

### APEX Nitro Version
4.1.6

### Operating System
mac os x 10.15 -beta 4

### Node Version
node version v10.15.3

### Browser
chrome 

### APEX Version
19.1

### Web Server
ords 18.2 +  tomcat 

This is the warning I keep getting.

```
is compiling sharples ...

  Replace Autoprefixer browsers option to Browserslist config.
  Use browserslist key in package.json or .browserslistrc file.

  Using browsers option cause some error. Browserslist config 
  can be used for Babel, Autoprefixer, postcss-normalize and other tools.

  If you really need to use option, rename it to overrideBrowserslist.

  Learn more at:
  https://github.com/browserslist/browserslist#readme
  https://twitter.com/browserslist


...Done!
...Now publishing!

```

Now I clicked on the link and it said I should set the browserlist in my package.json which I have done but I still get this error / warning.

The javascript and less still builds and deploys so as far as I know I don't think it creating errors.

Below is what I added to my package.json. 

```
 "browserslist": [
    "defaults"
  ]
```

**Comment by vincentmorneau** [comment]
Thanks for documenting this. You won't have to do this in APEX Nitro v5.
