### ISSUE TITLE
Error [ERR_UNHANDLED_ERROR]: Unhandled error. ([object Object]) at Gulp.emit (events.js:178:17)

### ISSUE THREAD

**Issue by JoseArostegui** [OraOpenSource/apex-nitro#308]
### Issue Description
Hi! I've testing Apex Nitro and I've been able to get a basic configuration up and running OK. But, when I switch to an advanced config and just enter the mandatory dist folder path, and left rest by default, I get this error:

is compiling advanced ...
C:\Users\Jose\AppData\Roaming\npm\node_modules\apex-nitro\node_modules\async-done\index.js:18
    throw err;
    ^

Error [ERR_UNHANDLED_ERROR]: Unhandled error. ([object Object])
    at Gulp.emit (events.js:178:17)
    at Gulp.EventEmitter.emit (domain.js:441:20)
    at Object.error (C:\Users\Jose\AppData\Roaming\npm\node_modules\apex-nitro\node_modules\undertaker\lib\helpers\createExtensions.js:61:10)
    at handler (C:\Users\Jose\AppData\Roaming\npm\node_modules\apex-nitro\node_modules\now-and-later\lib\mapSeries.js:47:14)
    at f (C:\Users\Jose\AppData\Roaming\npm\node_modules\apex-nitro\node_modules\once\once.js:25:25)
    at f (C:\Users\Jose\AppData\Roaming\npm\node_modules\apex-nitro\node_modules\once\once.js:25:25)
    at tryCatch (C:\Users\Jose\AppData\Roaming\npm\node_modules\apex-nitro\node_modules\async-done\index.js:24:15)
    at done (C:\Users\Jose\AppData\Roaming\npm\node_modules\apex-nitro\node_modules\async-done\index.js:40:12)
    at Domain.onError (C:\Users\Jose\AppData\Roaming\npm\node_modules\apex-nitro\node_modules\async-done\index.js:51:5)
    at Object.onceWrapper (events.js:277:13)

Surely I'm doing something wrong, but please help, I think this is a very powerful tool that I need my team to learn.
Regards,
Jose.

### APEX Nitro Version
v5.0.0-1

### Operating System
Windows 10 Pro

### Node Version
v10.15.1

### Browser
Version 77.0.3865.90 (Official Build) (64-bit)

### APEX Version
19.1

### Web Server
19.2.0.r1991647, Tomcat 7

### Project configuration screenshot
Configuration is just a basic running + add the distFolder path and save

**Comment by JoseArostegui** [comment]
If I try to launch the project again, I get this warnings and the sincro is not running when saving .css or .js in local PC:
...
is compiling advanced ...

  Replace Autoprefixer browsers option to Browserslist config.
  Use browserslist key in package.json or .browserslistrc file.

  Using browsers option cause some error. Browserslist config
  can be used for Babel, Autoprefixer, postcss-normalize and other tools.

  If you really need to use option, rename it to overrideBrowserslist.

  Learn more at:
  https://github.com/browserslist/browserslist#readme
  https://twitter.com/browserslist
...Done!
...Now launching!

Best regards,
Jose.

**Comment by vincentmorneau** [comment]
Hi Jose,

I'd love to help. You're using APEX Nitro v5 beta right now. I hope to get it done soon, but meanwhile do you mind rolling back to v4 ?

**Comment by JoseArostegui** [comment]
Hi Vincent,
Sure not problem to downgrade, but please tell me how... pretty new with node.js!
Truly congrats for your work, it's awesome.
Regards,
Jose.

**Comment by JoseArostegui** [comment]
**C:\WINDOWS\system32>npm view apex-nitro versions**
[ '4.0.0-beta.1',
  '4.0.0-beta.2',
  '4.0.0-beta.3',
  '4.0.0-beta.4',
  '4.0.0-beta.5',
  '4.0.0',
  '4.1.0-beta.1',
  '4.1.0-beta.2',
  '4.1.0-beta.3',
  '4.1.0-beta.4',
  '4.1.0',
  '4.1.1',
  '4.1.2',
  '4.1.3',
  '4.1.4',
  '4.1.5',
  '4.1.6',
  '4.2.0-beta.1',
  '5.0.0-1' ]
  
**cd c:\Users\Jose\AppData\Roaming\npm\node_modules**

**c:\Users\Jose\AppData\Roaming\npm\node_modules>npm uninstall apex-nitro**
npm WARN saveError ENOENT: no such file or directory, open 'c:\Users\Jose\AppData\Roaming\npm\package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN enoent ENOENT: no such file or directory, open 'c:\Users\Jose\AppData\Roaming\npm\package.json'
npm WARN npm No description
npm WARN npm No repository field.
npm WARN npm No README data
npm WARN npm No license field.

removed 1119 packages in 42.117s
found 0 vulnerabilities

**c:\Users\Jose\AppData\Roaming\npm\node_modules>npm install apex-nitro@4.1.6**

**Comment by JoseArostegui** [comment]
Hi Vincent,

After downgrading, I've
1) Create a new basic config. Tested running fined
2) Change to advanced and enter distributable folder path
3) Launch configuration and now I don't get the exception but this error:

  _Replace Autoprefixer browsers option to Browserslist config.
  Use browserslist key in package.json or .browserslistrc file.

  Using browsers option cause some error. Browserslist config
  can be used for Babel, Autoprefixer, postcss-normalize and other tools.

  If you really need to use option, rename it to overrideBrowserslist.

  Learn more at:
  https://github.com/browserslist/browserslist#readme
  https://twitter.com/browserslist_

And again, changes are not synchronized automatically.

Thanks for your help,
Jose.

**Comment by vincentmorneau** [comment]
The browsersync warning will be gone in v5, but I don't understand why the changes would not synchronize automatically.

I'm flagging this as a bug fix for v5, unless you can provide more info.

**Comment by JoseArostegui** [comment]
Hi Vincent,
Eager to help you to solve the issue and finally start using Apex Nitro with my team.
I'm having the problem both with v4.1.6 and v5.
Don't hesitate to ask for any trace or whatever, any time.
Regards,
Jose.

**Comment by JoseArostegui** [comment]
Hi Vincent,

Closing this issue means that it is solved? (sorry, I'm total novice in GitHub)...

Thanks,
Jose.

**Comment by vincentmorneau** [comment]
Yes, it has been solved for v5, but it's not published yet. I will make the official announcement.

**Comment by JoseArostegui** [comment]
Great! Thanks.
