### ISSUE TITLE
Doubt about DB user credentials

### ISSUE THREAD

**Issue by yevon** [OraOpenSource/apex-nitro#309]
### Issue Description
The DDBB user and password required does need any special privileges? Or related apex_admin role? Or I just can use any user schema that is defined at apex workspace level?

I'm receiving an alert that the process can't find my application ID. Any ideas? Thanks for your work.

### APEX Nitro Version
5.0.0-1

### Operating System
Windows

### Node Version
Latest

### Browser
Latest chrome

### APEX Version
[Example: v5.1.4]

### Web Server
ORDS

**Comment by vincentmorneau** [comment]
Yes, you can use any user schema that is defined at apex workspace level.

Can you show me the error?

Also you are using APEX Nitro v5.0.0-1, and I have to admit the documentation still points to v4.x

**Comment by yevon** [comment]
![image](https://user-images.githubusercontent.com/121157/66578014-a64b4900-eb7a-11e9-930c-0f6bc5b3816d.png)


Where can I find v5.0.0-1 documentation? Thanks!

**Comment by vincentmorneau** [comment]
Still needs to be written :)

**Comment by yevon** [comment]
Ignore this, It seems to be a missing permissions issue. Thanks!
