### ISSUE TITLE
Initializing a Plug-in project in v5.0.0-1

### ISSUE THREAD

**Issue by stefandobre** [OraOpenSource/apex-nitro#310]
I tried testing the new 5.0.0-1 architecture but I got stuck when initializing an APEX plug-in project. At which step during **apex-nitro init** do I provide the plug-in internal name? I also don't see an appropriate key for it inside apexnitro.config.json

**Comment by vincentmorneau** [comment]
Yup, sorry for the lack of documentation. I am trying to wrap things up now.
