### ISSUE TITLE
Auto Refresh if no node_modules are found

### ISSUE THREAD

**Issue by martindsouza** [OraOpenSource/apex-nitro#318]
Related to #317 : The use case is that `node_modules` is/should not be part of the code repository. When a developer does a `git clone` of the code base and they want to run `apex-nitro launch` automatically they'll get an error since all the packages are missing. To help avoid confusion can we detect that `apex-nitro refresh` should be triggered if certain files are missing (ex `node_modules`). This is one less step / point of confusion that developers need to worry about.

**Comment by vincentmorneau** [comment]
Fixed in 2966c884284cbebec0b7d3d1ed6eb962be277608
