### ISSUE TITLE
Optional to build min files on launch

### ISSUE THREAD

**Issue by martindsouza** [OraOpenSource/apex-nitro#319]
When running APEX Nitro 5 in docker using the CSS and Sass implementation it takes a while to re-compile the JS (this is just using the demo `greeting` function that comes with template. Times are upwards of around 3~5s (_I will look into seeing if something can be done on the docker side to make it run faster)_

When I'm developing with `apex-nitro launch` it builds both the `app.js` and `app.min.js`. Given that I'm in a "dev mode" I don't need to incur the cost of the `min.js` each time (see screenshot below). Is it possible to pass in a parameter (or something similiar) to say `-no-min` so it'll skip that step?

<img width="463" alt="image" src="https://user-images.githubusercontent.com/2925726/70752455-e4d2c080-1cef-11ea-877c-110c66426a14.png">

**Comment by vincentmorneau** [comment]
One problem here is that a lot of people including myself start Nitro without authenticating to the APEX builder. That sets APEX into prod mode, and loads the min files automatically.

We could add a no-min flag, but it seems like it would create another potential problem for users. That would also be hard to debug for people if they forget.

@martindsouza thoughts?

**Comment by vincentmorneau** [comment]
I would also argue the problem is in the build time. I should look into improving the speed. 5seconds for the demo code is not good.

**Comment by martindsouza** [comment]
If `no-min` flag can be an option to pass into the CLI that's fine with me. This will allow us to control the difference between Nitro during development than building a release.

**Comment by vincentmorneau** [comment]
Ok that works
