### ISSUE TITLE
Docs (and home page)

### ISSUE THREAD

**Issue by martindsouza** [OraOpenSource/apex-nitro#320]
Nitro 5.0. The home page has the example:

```
#APP_IMAGES#myproject.js
#APP_IMAGES#myproject.css
```

Should these be

```
#APP_IMAGES#myproject#MIN#.js
#APP_IMAGES#myproject#MIN#.css
```

instead?

Related tickets:

- #314 for using default `app.js` and `app.css`
- #315 would be part of the image makeovers

**Comment by martindsouza** [comment]
@vincentmorneau it wasn't about the app name rather to use the `#MIN#` version or not.

**Comment by vincentmorneau** [comment]
I misread. You are right. Will fix.
