### ISSUE TITLE
debounce on file change

### ISSUE THREAD

**Issue by vincentmorneau** [OraOpenSource/apex-nitro#325]
to avoid 100x recompiling if multiple files are changed at the same time (checking in a branch, batch search and replace)

**Comment by difr** [comment]
Hello, Vincent!
You can take https://github.com/difr/apex-nitro/commit/dcd37695f85405a2d759646334f621ed43c52d6f
to fix this.

**Comment by vincentmorneau** [comment]
@difr what is `process.env.SINGLE_BUNDLE` in your code?

**Comment by difr** [comment]
@vincentmorneau
coz i use single repo for whole project, there are all developing libs/pages in single rollup config.
so if i'm currently working only with 1 of them i don't need to rebuild all untouched (it takes too much time), so i use SINGLE_BUNDLE=pageXXX and it rebuilds only pageXXX
