### ISSUE TITLE
make sure distFolder is not in srvFolder

### ISSUE THREAD

**Issue by emoracle** [OraOpenSource/apex-nitro#327]
### Issue Description
When you define the distFolder as a subfolder of the srcFolder you will get stuck in a loop. The dist folder will be written in the source folder, which will trigger the "other" part of the browsersync gulp task, wich will write a dist folder in the dist folder, which will trigger the "other" etc etc.

You should check for this situation

### APEX Nitro Version
Encountered in 4.16

### Operating System
Windows 10

### Node Version
12.14.1

### Browser
Chrome 79

**Comment by vincentmorneau** [comment]
Good point. Thanks.
