### ISSUE TITLE
403 - Forbidden

### ISSUE THREAD

**Issue by marvinamorim** [OraOpenSource/apex-nitro#328]
### Issue Description
Hello.
I was able to make apex-nitro work perfectly with an Apex that I installed using the Oxar from OraOpenSource.
But when I try to use apex-nitro with my company Apex (that was installed by a third part DBA support) I have my access forbidden when I run `apex-nitro launch`:
```
HTTP 403 : Forbidden
The request cannot be processed because this resource does not support Cross Origin Sharing requests, or the request Origin is not authorized to access this resource. If ords is being reverse proxied ensure the front end server is propagating the host name, for mod_proxy ensure ProxyPreserveHost is set to On
```
I wasn't able to find any parameter called `ProxyPreserveHost` on any tomcat config file (on both my Oxar Apex or my company Apex).
Every test that I done was using the basic mode.
There is anything that I can try in order to allow "Cross Origin Sharing requests" on my tomcat, besides this parameter that I can't find?

### APEX Nitro Version
Tested on both 4.1.6 and 5.0.0-1

### Operating System
Windows 10 Pro 64 bits

### Node Version
Node.js v12.14.1

### Browser
Chrome v80.0.3987.87
Firefox v72.0.2

### APEX Version
Both 19.1 and 19.2

### Web Server
Worked on: `ORDS 18.1.1.95.1251` and `Tomcat 7.0.76`
Didn't work on: `ORDS 19.2.0.r1991647` and `Tomcat 8.5.9`

**Comment by vincentmorneau** [comment]
I need to investigate further, but this looks relevant for you: https://community.oracle.com/thread/4278450 

Can you look into it and report back?

**Comment by marvinamorim** [comment]
Sure, I will look at this thread and see if there is anything that might help and will report back.

Thanks.

**Comment by difr** [comment]
@vincentmorneau @marvinamorim
i've fixed it such way
https://github.com/difr/apex-nitro/commit/b0b0290729d7f6747dde4309a24c2617e80e53bc

and here it appeared
https://github.com/OraOpenSource/apex-nitro/commit/c2b35b4021fa2a2bbda36b7758a60b68e5c9b501#r36559737

**Comment by marvinamorim** [comment]
Hello.
> difr@b0b0290
This fixed the problem and now the `launch` fuction is working, and I don't get more "Forbidden" problem when proxing.

Thanks @difr @vincentmorneau for all your help. Now my life as apex dev is better :)

**Comment by vincentmorneau** [comment]
Thanks @difr , I'll merge that to master.
