### ISSUE TITLE
Is there any way to ignore a given folder when publishing the assets?

### ISSUE THREAD

**Issue by rafael-trevisan** [OraOpenSource/apex-nitro#329]
Hi all,

I have a repository where we have more than one APEX app. The repo is something like:

```
src
  api
  app
    app-1
      apex
      assets
      js
      scss
    app-2
      apex
      assets
      js
      scss
  db
  ...
```
The structure works very well for a variety of purposes we have. However, having NITRO source folder at `app-1` or `app-2` causes the publish to upload the APEX source files into the APEX app which takes a very long time and pollutes the app.

I wish I could tell Nitro to ignore the `apex` folder within the "source" folder so it'd only upload the `assets`, `css` and `js` folder.

Would there by any suggestion on how to achieve this?

Thanks in advance.

**Comment by vincentmorneau** [comment]
Hey Rafael,

This is a common scenario, having two apps under the same project repo. I suggest you think of your directory structure differently.

src
  api
  app
    app-1
      apex
      www
         assets
         js
         scss
    app-2
      apex
      www
         assets
         js
         scss
  db
  ...

Then you can upload app-1/www and app-2/www separately. It really makes sense to have two dedicated app folders to Nitro here.

**Comment by rafael-trevisan** [comment]
I see. Yeah, I'll see to change the structure over here.
