### ISSUE TITLE
Different relative path with .css and .min.css

### ISSUE THREAD

**Issue by rafael-trevisan** [OraOpenSource/apex-nitro#330]
Hi all,

I have my `app.scss` file like:

```
background-image:url('../../images/image.jpg');
```

The `app.css` gets correctly compiled into:
```
background-image:url('../../images/image.jpg');
```

But the `app.min.css` gets "wrongly" (always missing a level in the path) compiled to: 
```
background-image:url(../images/image.jpg);
```

I am using the #MIN# in APEX, so I can successfully see my `css` in the app while developing/testing, but when I run the app without the builder, my style won't be there.

**Comment by vincentmorneau** [comment]
It is confusing indeed, but given Nitro move from `source` folder to the `build` folder, we have to think a little differently.

Here an example source folder:

```
/js/
  file1.js
/css/
  file1.css
/static/
  image1.jpg
main.js
```

it will compile to

```
/static/
  image1.jpg
main.js
main.css
```

where the rule should be

`background-image:url('./static/image1.jpg');`

So by keeping the final state in mind, you are able to code your source accordingly.
