### ISSUE TITLE
No minifying and concatenation of the JS & CSS files

### ISSUE THREAD

**Issue by meeuwtjes** [OraOpenSource/apex-nitro#333]
### Issue Description
After I have setup my apex-nitro installation and launched the project, the files in the source directory are not minified and concatenated in the build files
All the files that exist in src directory are copied to the build and not minified

I also tried it with version v5, but it only uses main.css/ main.js from src directory and no minifying 

When I launch the project it shows the following message in command window:
(node:20132) [DEP0066] DeprecationWarning: OutgoingMessage.prototype._headers is deprecated
Maybe this matters?

### APEX Nitro Version
4.1.6

### Operating System
Windows x64

### Node Version
12.18.1 (npm 6.14.5)

### Browser
Firefox 77.0.1

### APEX Version
20.1.0.00.13

### Web Server
ORDS 19.4.6

### Project configuration screenshot
**Version 4**
{
  "apexnitrov4": {
    "mode": "advanced",
    "appURL": "http://devwls03.nl.aswatson.net:8888/aswmso_194/f?p=109",
    "srcFolder": "d:\\Algemeen\\apexnitrov4\\src",
    "distFolder": "d:\\Algemeen\\apexnitrov4\\build",
    "js": {
      "processor": "default",
      "concat": true,
      "concatFilename": "apexnitrov4",
      "tsConcat": false
    },
    "css": {
      "language": "css",
      "concat": true,
      "concatFilename": "apexnitrov4"
    },
    "browsersync": {
      "realTime": true,
      "ghostMode": true,
      "notify": true
    },
    "header": {
      "enabled": true,
      "packageJsonPath": "d:\\Algemeen\\apexnitrov4\\package.json"
    },
    "apex": {
      "openBuilder": false
    },
    "publish": {
      "destination": "application"
    }
  }
}

**Version v5**
{
  "mode": "pro",
  "template": "apex-nitro-template-js",
  "projectName": "APEXNITRO",
  "libraryName": "APEXNITRO",
  "main": "./src/main.js",
  "globals": {
    "apex": "apex"
  },
  "srcFolder": "./src",
  "distFolder": "./build",
  "external": [
    "apex"
  ],
  "cssExtensions": [
    ".css",
    ".styl "
  ],
  "version": "1.0.0",
  "appUrl": "http://devwls03.nl.aswatson.net:8888/aswmso_194/f?p=109",
  "browsersync": {
    "defaults": "custom",
    "port": 4000,
    "realTime": true,
    "ghostMode": true,
    "notify": true
  },
  "apex": {
    "openApp": true,
    "openBuilder": false
  },
  "publish": {
    "defaults": "custom",
    "destination": "application",
    "path": "sqlcl",
    "username": "",
    "password": "",
    "connectionString": ""
  }
}

**Comment by vincentmorneau** [comment]
The deprecation message is being fixes already.

Your configs for both v4 and v5 look fine. I'm surprised you are able to get to the end of the build process without any errors, AND that the minification doesn't happen.

I'll be actively working to release v5 this week, so I'll close this for now but feel free to reopen with more questions.
