### ISSUE TITLE
I can't install apex-nitro with node-v12.18.2

### ISSUE THREAD

**Issue by AmrAbdeen** [OraOpenSource/apex-nitro#335]
### Issue Description
This is the first time install it
Once i upgrade my Node to last stable one and executed $ _sudo npm install -g apex-nitro_
I found that ...

> 
> gyp ERR! configure error 
> gyp ERR! stack Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/apex-nitro/node_modules/node-sass/.node-gyp'
> gyp ERR! System Darwin 19.5.0
> gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/apex-nitro/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
> gyp ERR! cwd /usr/local/lib/node_modules/apex-nitro/node_modules/node-sass
> gyp ERR! node -v v12.18.2
> gyp ERR! node-gyp -v v3.8.0
> gyp ERR! not ok 
> Build failed with error code: 1
> npm WARN notsup Unsupported engine for watchpack-chokidar2@2.0.0: wanted: {"node":"<8.10.0"} (current: {"node":"12.18.2","npm":"6.14.5"})
> npm WARN notsup Not compatible with your version of node/npm: watchpack-chokidar2@2.0.0
> 
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! node-sass@4.14.1 postinstall: `node scripts/build.js`
> npm ERR! Exit status 1
> npm ERR! 
> npm ERR! Failed at the node-sass@4.14.1 postinstall script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /Users/amrahmed/.npm/_logs/2020-07-06T13_25_05_614Z-debug.log
> 
> 

### APEX Nitro Version
Latest one

### Operating System
Mac Catalina v10.15

### Node Version
v12.18.2

### Browser
[Example: Chrome v50]

### APEX Version
[Example: v5.1.1]

### Web Server
[Example: ORDS 3.0.9, Tomcat 7]

### Project configuration screenshot
[Paste image]
https://www.loom.com/share/5732a769613648a2928f8d21dbc5b86e

**Comment by vincentmorneau** [comment]
You should not use sudo while installing apex-nitro globally.

**Comment by vincentmorneau** [comment]
I could not reproduce without sudo.
