### ISSUE TITLE
sources map files are not uploaded to apex static files & source map files of min files are not generated

### ISSUE THREAD

**Issue by elsayedaliosman** [OraOpenSource/apex-nitro#339]
### Issue Description
sources map files are not uploaded to apex static files & source map files of min files are not generated

### APEX Nitro Version
[v4.1.6]

### Operating System
[Windows]

### Node Version
[v12.18.3]

### Browser
[Chrome]

### APEX Version
[v19.2.0.00.18]

### Project configuration screenshot
{
  "apex_nitro": {
    "mode": "advanced",
    "appURL": "http://hostname:port/ords/f?p=104",
    "srcFolder": "C:\\Users\\username\\projects\\Apex_Nitro\\src",
    "distFolder": "C:\\Users\\username\\projects\\Apex_Nitro\\dist",
    "js": {
      "processor": "default",
      "concat": false,
      "tsConcat": false
    },
    "css": {
      "language": "css",
      "concat": false
    },
    "browsersync": {
      "realTime": true,
      "ghostMode": true,
      "notify": true
    },
    "header": {
      "enabled": false
    },
    "apex": {
      "openBuilder": true
    },
    "publish": {
      "destination": "application",
      "path": "C:\\Software\\sqlcl\\bin\\sql",
      "connectionType": "basic",
      "username": "******",
      "password": "******",
      "host": "******",
      "port": "******",
      "basicType": "service name",
      "serviceName": "******"
    }
  }
}

**Comment by vincentmorneau** [comment]
Sourcemaps will be generated on dev files (not min). 
Sourcemaps should not be generated on min files, as it slows down the output at runtime and gives too much info on the code.
