### ISSUE TITLE
403 Forbidden CORS errors with a new empty project

### ISSUE THREAD

**Issue by JoseArostegui** [OraOpenSource/apex-nitro#347]
### Issue Description
403 Forbidden
The request cannot be processed because this resource does not support Cross Origin Sharing requests, or the request Origin is not authorized to access this resource. If ords is being reverse proxied ensure the front end server is propagating the host name, for mod_proxy ensure ProxyPreserveHost is set to On

### APEX Nitro Version
v5.0.2

### Operating System
Windows 10

### Node Version
v14.15.1

### Browser
Chrome Version 87.0.4280.66 (Official Build) (64-bit)

### APEX Version
20.2

### Web Server
ORDS 19.2.0.r1991647, Tomcat 8

**Comment by JoseArostegui** [comment]
Hi,

I'm a newbie, sorry for the inconvenience this is my apexnitro.config.json

{
  "mode": "basic",
  "appName": "HeroIMT",
  "appUrl": "http://xxxxx.josearostegui.com:8080/ords/f?p=500",
  "srcFolder": "./src",
  "launch": {
    "port": 4000,
    "ghostMode": false,
    "notify": true,
    "open": true,
    "openBuilder": false
  },
  "upload": {
    "destination": "application",
    "credentialsPath": "./apexnitro.cred.json"
  }
}

When I run apex-nitro launch, I get the CORS error in the browser, but nothing else is displayed in msdos console:

C:\......>apex-nitro launch
APEX Nitro
...Now launching!
Open up your favorite code editor to C:\srcHeroApexIMT\trunk\Hero-Applications\Applications\IMT\apex-nitro\src
Any change you make is synchronized to your APEX app in real time.
Watching for changes...
[APEX Nitro] Proxying: http://xxxxxx.josearostegui.com:8080
[APEX Nitro] Access URLs:
 ------------------------------------------------
    Local: http://localhost:4000/ords/f?p=500
 External: http://192.168.0.149:4000/ords/f?p=500
 ------------------------------------------------

**Comment by JoseArostegui** [comment]
Hi,

I've solved this problem by setting up an nginx as a reverse proxy, listening into 443 port and avoiding port 8080 and seems to work fine.

But, now, when trying to run "apex-nitro upload" I get:

java.sql.SQLException: ORA-20001: Application ps is not valid.
ORA-06512: en línea 1

Any ideas?

Thanks,
Jose.

**Comment by JoseArostegui** [comment]
Hi,

Solved the previos issue, it was due to an error in parameter "appUrl" where I was missing the f?p=500 section.

The final issue for me is that I have only these two files:
".\src\HeroIMT.css"
".\src\HeroIMT.js"

But only it's been uploaded the .css but NOT the .js:

```
C:\srcHeroApexIMT\trunk\Hero-Applications\Applications\IMT\imt-apex-nitro>apex-nitro upload
APEX Nitro
Your project is using Basic mode, so there is nothing to build.
Change your project to Pro mode or execute apex-nitro launch.
...Now uploading!
Uploading to 500 - Application Static Files...

SQLcl: Version 20.2 Production en lun dic 14 11:02:29 2020

Copyright (c) 1982, 2020, Oracle. Todos los derechos reservados.
Conectado a:
Oracle Database 18c Express Edition Release 18.0.0.0.0 - Production
Version 18.4.0.0.0
Uploaded: C:\srcHeroApexIMT\trunk\Hero-Applications\Applications\IMT\imt-apex-nitro\src\HeroIMT.css
SQL>
Desconectado de Oracle Database 18c Express Edition Release 18.0.0.0.0 - Production
Version 18.4.0.0.0
Files were uploaded successfully.

```
The automatic reloading of the .js is fine and tested that the pages are using the .js by checking the console in the browser and adding some console.log sentences.
Thanks,
Jose.

**Comment by JoseArostegui** [comment]
Closing this issue (without any answer from your side), as I think my issue is the same than number #334.

About the .js not being uploaded, I've created a separated issue #351

Thanks,
Jose.

**Comment by vincentmorneau** [comment]
Thank you and sorry again for the slowness. I will address the other issue.
